# Generated by Django 4.2.10 on 2024-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='item', to='api.category'),
        ),
    ]
