# Generated by Django 4.2.10 on 2024-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.IntegerField(),
        ),
    ]
