# Generated by Django 4.2.10 on 2024-02-24 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_page_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.book'),
        ),
    ]
