# Generated by Django 4.2.10 on 2024-02-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='acquisition_date',
        ),
    ]
