# Generated by Django 4.2.10 on 2024-03-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_item_acquisition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='book', to='api.genre'),
        ),
    ]
